services:
  _defaults:
    public: true
  ecoffrefort.coffre_map:
    class: Consoneo\Bundle\EcoffreFortBundle\CoffreMap
    arguments:
      - ~

  ecoffrefort.tiers_archivage_map:
    class: Consoneo\Bundle\EcoffreFortBundle\TiersArchivageMap
    arguments:
      - ~