services:
  _defaults:
    public: true

  ecoffrefort.coffre_map:
    class: Consoneo\Bundle\EcoffreFortBundle\CoffreMap
    arguments:
      - ~

  ecoffrefort.tiers_archivage_map:
    class: Consoneo\Bundle\EcoffreFortBundle\TiersArchivageMap
    arguments:
      - ~

  Consoneo\Bundle\EcoffreFortBundle\Command\DelCommand:
    arguments:
      - '@ecoffrefort.tiers_archivage_map'
    tags:
      - { name: console.command }

  Consoneo\Bundle\EcoffreFortBundle\Command\ListCommand:
    arguments:
      - '@ecoffrefort.tiers_archivage_map'
    tags:
      - { name: console.command }

  Consoneo\Bundle\EcoffreFortBundle\Command\PutCommand:
    arguments:
      - '@ecoffrefort.tiers_archivage_map'
    tags:
      - { name: console.command }

  sonata.admin.ecoffrefort.logquery:
    class: Consoneo\Bundle\EcoffreFortBundle\Admin\LogQueryAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, label: LogQuery, model_class: Consoneo\Bundle\EcoffreFortBundle\Entity\LogQuery }

  sonata.admin.ecoffrefort.annuaire:
    class: Consoneo\Bundle\EcoffreFortBundle\Admin\AnnuaireAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, label: Annuaire, model_class: Consoneo\Bundle\EcoffreFortBundle\Entity\Annuaire, controller: Consoneo\Bundle\EcoffreFortBundle\Controller\CRUDController }
